version: "2"
linters:
  exclusions:
    rules:
    # Ignore errcheck for defer ctx.Close()
    #
    - linters:
        - errcheck
      text: "Error return value of `.*\\.Close` is not checked"
      source: "defer.*\\.Close\\(\\)"
    - linters:
        - errcheck
      text: "Error return value of `.*\\.Close` is not checked"
      source: "ctx.Close\\(\\)"
